name: build-and-push

on:
  workflow_call:
    inputs:
      IMAGE_PROJECT:
        required: true
        type: string
        description: "Docker image project"
      IMAGE_NAME:
        required: true
        type: string
        description: "Docker image name"
      MAJOR:
        required: true
        type: string
        description: "Semantic major version"
      MINOR:
        required: true
        type: string
        description: "Semantic minor version"
      PATCH:
        required: true
        type: string
        description: "Semantic patch version"
      REGISTRY:
        required: false
        type: string
        description: "Docker registry URL"
        default: harbor.fumo.jp
      USERNAME:
        required: false
        type: string
        description: "Docker registry username"
        default: robot$github-actions
      CONTEXT:
        required: false
        type: string
        description: "Docker context"
        default: "./app"
      PUSH:
        required: false
        type: boolean
        description: "Push to registry"
        default: true
    secrets:
      PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_PROJECT }}/${{ inputs.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.MAJOR }}.${{ inputs.MINOR }}.${{ inputs.PATCH }}
            type=raw,value=${{ inputs.MAJOR }}.${{ inputs.MINOR }}
            type=raw,value=${{ inputs.MAJOR }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.CONTEXT }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max,image-manifest=true
          push: ${{ inputs.PUSH }}
